services:
  freqtrade-openclaw-btc-sr-trend-1d:
    build:
      context: .
      dockerfile: Dockerfile
    image: freqtrade-local:postgres
    container_name: freqtrade-openclaw-btc-sr-trend-1d
    restart: unless-stopped
    ports:
      - "8113:8113"
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade
      --config /freqtrade/user_data/config_openclaw-btc-sr-trend-1d.json
      --strategy OpenClawBtcSrTrend1d
      --db-url postgresql://bits:4642@host.docker.internal:5432/freqtrade_sr_trend_1d
