services:
  freqtrade-fibreversalspot-eth:
    build:
      context: .
      dockerfile: Dockerfile
    image: freqtrade-fibreversalspot-eth:local
    container_name: freqtrade-fibreversalspot-eth
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade
      --config /freqtrade/user_data/config_fibreversal_eth_spot.json
      --strategy FibReversalSpot_1h
