services:
  freqtrade-fibreversal-eth-futures:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-fibreversal-eth-futures
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8084:8084"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade-fibreversal-eth-futures.log
      --db-url sqlite:////freqtrade/user_data/trades-fibreversal-eth-futures.sqlite
      --config /freqtrade/user_data/config_fibreversal_eth_futures.json
      --strategy VolumeSrTrendReversalETH15m
