services:
  freqtrade-patternrecognition-btc:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-patternrecognition-btc
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8091:8091"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade-patternrecognition-btc.log
      --db-url sqlite:////freqtrade/user_data/trades-patternrecognition-btc.sqlite
      --config /freqtrade/user_data/config_patternrecognition_btc.json
      --strategy PatternRecognition
